### ISSUE TITLE
Make the whole process bearable please

### ISSUE THREAD

**Issue by jerkstore369** [TheLX5/Powerups#50]
Wtf is this, seriosuly? Download this app, download that, save a level, stick your left foot out, do the hokey pokey and turn yourself around. This is so archaic and nobody normal is going to attempt this. You're leaving the average user out to dry. Just make one app that does all this automatically that includes all the tools. Just have the user select the rom and that's it. Jesus Christ.

**Comment by TheLX5** [comment]
You can always use one of the attached bps files and apply it directly to a clean SMW USA ROM with [Floating IPS](https://www.smwcentral.net/?p=section&a=details&id=11474) and you would have the powerups in your ROM without following the installation guide. However, I don't recommend doing that since it locks you out from some features such as: inserting custom sprites, blocks and music without breaking the powerups (crashes, visual glitches, etc), plus not being able to have proper tooltips in Lunar Magic.

This whole package of ASM hacks, as stated in the [Installation Guide](https://github.com/TheLX5/Powerups/wiki/2.-Installation), requires you have some knowledge about SMW Hacking and some of its main tools. I suggest reading some [tutorials](https://www.smwcentral.net/?p=viewforum&f=1939) about them in SMWC's forums if you want to install everything manually.

Making an app is a no from me since I lack the programming skills to do it (I only program in ASM and a little bit of Python) and it's very likely that said app would require downloading the things stated in the Installation Guide anyway. It's not worth my time.

**Comment by jerkstore369** [comment]
I didn't even know about inserting custom sprites or any of that. I just wanted to play a new version of smw - it looked really cool - not really interested in fiddling around with the rom or anything. So if I just want to play it, I can simply apply a bps file? Which one is it? It probably should be made clear at the beginning of the instructions that if you just want to play you can apply a patch and specify which one. Anyways, thanks.

**Comment by TheLX5** [comment]
Yup, this project is aimed to create levels with custom powerups, the bps patches just simplifies the installation but has some drawbacks.

You may have some luck asking on SMWC for some SMW hacks that makes use of this patch, since I haven't kept track of which hacks have used this project.
